# k8s/deployment.yaml
spec:
  template:
    spec:
      containers:
      - name: nim-inference
        image: your-registry/nim-inference:latest
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
        - name: DEVICE
          value: "cpu"
        - name: FALLBACK_TO_CPU
          value: "true"